name: CI-with-CML
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://dvcorg/cml-py3:latest
    steps:
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: actions/checkout@v2
      - name: running cml
        env:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirement.txt
          python main.py
          echo "Model Metrics"
          cat results.txt
          echo "## Model metrics" > report.md
          cat results.txt >> report.md

          echo "## Plots" >> report.md
          echo "### Loss" >> report.md
          cml-publish loss.png --md >> report.md

          echo "### Accuracy" >> report.md
          cml-publish acc.png --md >> report.md

          cml-send-comment report.md
